# Generated by Django 5.2.12 on 2026-06-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001 initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_date',
            field=models.DateField(verbose_name='Shartnoma sanasi'),
        ),
    ]
