# Generated by Django 5.2.12 on 2026-05-06 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', 'queue_migration_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuesettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
