# Generated by Django 5.2.12 on 2026-06-23 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0032_patientcard_case_sheet_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('unit', models.CharField(default='dona', max_length=20, verbose_name='Birlik')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Narxi (so'm)")),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sarflanadigan material',
                'verbose_name_plural': 'Sarflanadigan materiallar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=30, unique=True, verbose_name='Hisob-faktura raqami')),
                ('status', models.CharField(choices=[('unpaid', "To'lanmagan"), ('partial', "Qisman to'langan"), ('paid', "To'liq to'langan"), ('cancelled', 'Bekor qilingan')], default='unpaid', max_length=10, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='patients.patientcard', verbose_name='Bemor kartasi')),
            ],
            options={
                'verbose_name': 'Hisob-faktura',
                'verbose_name_plural': 'Hisob-fakturalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Chegirma summasi (so'm)")),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Sababi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="Kim qo'shdi")),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='billing.invoice', verbose_name='Hisob-faktura')),
            ],
            options={
                'verbose_name': 'Chegirma',
                'verbose_name_plural': 'Chegirmalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('invoice_created', 'Hisob-faktura yaratildi'), ('payment_added', "To'lov qo'shildi"), ('discount_added', "Chegirma qo'shildi"), ('refund_added', "Qaytarish qo'shildi"), ('consumable_added', "Material qo'shildi"), ('recalculated', 'Qayta hisoblandi'), ('status_changed', "Holati o'zgardi")], max_length=20, verbose_name='Amal')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Kim bajardi')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='billing.invoice', verbose_name='Hisob-faktura')),
            ],
            options={
                'verbose_name': 'Audit yozuvi',
                'verbose_name_plural': 'Audit jurnali',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientConsumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Miqdori')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Narxi (so'm)")),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.consumable', verbose_name='Material')),
                ('ordered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="Kim qo'shdi")),
                ('patient_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_consumables', to='patients.patientcard', verbose_name='Bemor kartasi')),
            ],
            options={
                'verbose_name': 'Bemorga sarflangan material',
                'verbose_name_plural': 'Bemorga sarflangan materiallar',
                'ordering': ['-ordered_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Summa (so'm)")),
                ('method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Plastik karta'), ('bank_transfer', "Bank o'tkazmasi"), ('insurance', "Sug'urta")], default='cash', max_length=15, verbose_name="To'lov usuli")),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Kassir')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.invoice', verbose_name='Hisob-faktura')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Qaytarilgan summa (so'm)")),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Sababi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Kim qaytardi')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='billing.invoice', verbose_name='Hisob-faktura')),
            ],
            options={
                'verbose_name': 'Qaytarish (Refund)',
                'verbose_name_plural': 'Qaytarishlar (Refundlar)',
                'ordering': ['-created_at'],
            },
        ),
    ]
