# Generated by Django 5.2.12 on 2026-03-29 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0011_patientcard_is_pensioner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Kodi')),
                ('category_type', models.CharField(choices=[('lab', 'Laboratoriya'), ('radiology', 'Rentgen/UZI/MRT'), ('surgery', 'Jarrohlik'), ('physio', 'Fizioterapiya'), ('consultation', 'Konsultatsiya'), ('other', 'Boshqa')], default='other', max_length=20, verbose_name='Turi')),
                ('icon', models.CharField(blank=True, default='🏥', max_length=10, verbose_name='Ikona (emoji)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Xizmat kategoriyasi',
                'verbose_name_plural': 'Xizmat kategoriyalari',
                'ordering': ['category_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Xizmat nomi')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Kodi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsifi')),
                ('price_normal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Oddiy narx (so'm)")),
                ('price_railway', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Temir yo'lchi narxi (so'm)")),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.department', verbose_name="Mas'ul bo'lim")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Xizmat',
                'verbose_name_plural': 'Xizmatlar',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PatientService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Miqdori')),
                ('status', models.CharField(choices=[('ordered', 'Buyurtma berildi'), ('in_progress', 'Bajarilmoqda'), ('completed', 'Bajarildi'), ('cancelled', 'Bekor qilindi')], default='ordered', max_length=15, verbose_name='Holati')),
                ('ordered_at', models.DateTimeField(auto_now_add=True, verbose_name='Buyurtma sanasi')),
                ('performed_at', models.DateTimeField(blank=True, null=True, verbose_name='Bajarilgan sana')),
                ('result', models.TextField(blank=True, verbose_name='Natija / Xulosa')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Birlik narxi (so'm)")),
                ('patient_category_at_order', models.CharField(blank=True, max_length=15, verbose_name='Buyurtma paytidagi bemor kategoriyasi')),
                ('is_paid', models.BooleanField(default=False, verbose_name="To'langan")),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('ordered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_services', to='patients.doctor', verbose_name='Buyurtma bergan shifokor')),
                ('patient_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_services', to='patients.patientcard', verbose_name='Bemor kartasi')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_services', to='patients.doctor', verbose_name='Bajargan shifokor')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.service', verbose_name='Xizmat')),
            ],
            options={
                'verbose_name': 'Bemor xizmati',
                'verbose_name_plural': 'Bemor xizmatlari',
                'ordering': ['-ordered_at'],
            },
        ),
    ]
