# Generated by Django 5.2.12 on 2026-05-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='is_operation',
        ),
        migrations.AddField(
            model_name='service',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nomi (ruscha)'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nomi (ruscha)'),
        ),
    ]
