# Generated by Django 5.2.12 on 2026-05-08 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_service_is_operation_service_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_operation',
            field=models.BooleanField(default=False, verbose_name='Operatsiyami?'),
        ),
    ]
