# Generated by Django 5.2.12 on 2026-06-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_service_lab_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.CharField(choices=[('drug', 'Dori'), ('lab', 'Laboratoriya anjomi'), ('other', 'Boshqa')], default='drug', max_length=10, verbose_name='Kategoriya'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='dosage_form',
            field=models.CharField(blank=True, choices=[('tabletka', 'Tabletka'), ('kapsula', 'Kapsula'), ('eritma', 'Eritma (inyeksiya uchun)'), ('sirop', 'Sirop'), ('tomchi', 'Tomchi'), ('malham', 'Malham'), ('krem', 'Krem'), ('kukun', 'Kukun'), ('suspenziya', 'Suspenziya'), ('aerozol', 'Aerozol'), ('gel', 'Gel'), ('sham', 'Sham (suppozitoriy)'), ('patch', 'Patch (yopishtirgich)'), ('other', 'Boshqa')], max_length=20, verbose_name='Chiqarish shakli'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='mnn',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='МНН (xalqaro nomi)'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='strength',
            field=models.CharField(blank=True, max_length=100, verbose_name='Doza / konsentratsiya'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Savdo nomi'),
        ),
    ]
