# Generated by Django 5.2.12 on 2026-06-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0030_service_assignment_links'),
        ('services', '0008_medicine_mnn_form_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='assigned_doctors',
            field=models.ManyToManyField(blank=True, related_name='assignable_services', to='patients.doctor', verbose_name='Biriktirilgan shifokorlar'),
        ),
    ]
