# Generated by Django 5.2.12 on 2026-06-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_service_assignment_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmedicine',
            name='source',
            field=models.CharField(choices=[('hospital', "Bo'lim dorixonasi"), ('patient', "Bemor o'zi olib keldi")], default='hospital', max_length=10, verbose_name='Manba'),
        ),
    ]
