# Generated by Django 5.2.12 on 2026-06-29 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0045_ambulatoryconsultation_doctor_v2_and_more'),
        ('services', '0010_patientmedicine_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmedicine',
            name='ordered_by_v2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_medicines', to=settings.AUTH_USER_MODEL, verbose_name='Buyurtma bergan shifokor'),
        ),
        migrations.AddField(
            model_name='patientservice',
            name='ordered_by_v2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_services', to=settings.AUTH_USER_MODEL, verbose_name='Buyurtma bergan shifokor'),
        ),
        migrations.AddField(
            model_name='patientservice',
            name='performed_by_v2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_services', to=settings.AUTH_USER_MODEL, verbose_name='Bajargan shifokor'),
        ),
        migrations.AddField(
            model_name='service',
            name='assigned_doctors_v2',
            field=models.ManyToManyField(blank=True, related_name='assignable_services', to=settings.AUTH_USER_MODEL, verbose_name='Biriktirilgan shifokorlar'),
        ),
        migrations.AlterField(
            model_name='patientmedicine',
            name='ordered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_medicines_old', to='patients.doctor', verbose_name='Buyurtma bergan shifokor'),
        ),
        migrations.AlterField(
            model_name='patientservice',
            name='ordered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_services_old', to='patients.doctor', verbose_name='Buyurtma bergan shifokor'),
        ),
        migrations.AlterField(
            model_name='patientservice',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_services_old', to='patients.doctor', verbose_name='Bajargan shifokor'),
        ),
        migrations.AlterField(
            model_name='service',
            name='assigned_doctors',
            field=models.ManyToManyField(blank=True, related_name='assignable_services_old', to='patients.doctor', verbose_name='Biriktirilgan shifokorlar'),
        ),
    ]
