# Generated by Django 5.2.12 on 2026-07-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_doctor_field_swap'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='non_resident_surcharge',
            field=models.BooleanField(default=True, help_text='Yoqilsa — norezident uchun narx avtomatik 25% qimmatroq hisoblanadi.', verbose_name='Norezident +25%'),
        ),
    ]
