# Generated by Django 5.2.12 on 2026-05-20 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
        ('patients', '0021_add_transfer_date_to_patient_transfer'),
        ('services', '0007_service_lab_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='labparameter',
            name='is_required',
            field=models.BooleanField(default=True, verbose_name='Majburiy'),
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('partial', 'Qisman bajarildi'), ('completed', 'Bajarildi'), ('verified', 'Tasdiqlandi'), ('printed', 'Chop etildi')], default='pending', max_length=15, verbose_name='Holat')),
                ('ordered_at', models.DateTimeField(auto_now_add=True, verbose_name='Buyurtma vaqti')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('ordered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lab_orders', to=settings.AUTH_USER_MODEL, verbose_name='Buyurtma bergan')),
                ('patient_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='patients.patientcard', verbose_name='Bemor')),
            ],
            options={
                'verbose_name': 'Lab buyurtma',
                'verbose_name_plural': 'Lab buyurtmalar',
                'ordering': ['-ordered_at'],
            },
        ),
        migrations.CreateModel(
            name='LabOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('sample_taken', 'Namuna olindi'), ('in_progress', 'Jarayonda'), ('result_entering', 'Kiritilmoqda'), ('completed', 'Bajarildi'), ('verified', 'Tasdiqlandi'), ('printed', 'Chop etildi'), ('rejected', 'Rad etildi'), ('recollect', 'Qayta namuna kerak')], default='pending', max_length=20, verbose_name='Holat')),
                ('reject_reason', models.CharField(blank=True, choices=[('hemolyzed', 'Gemolizlangan namuna'), ('insufficient', 'Namuna yetarli emas'), ('wrong_tube', "Noto'g'ri quvurcha"), ('clotted', 'Ivigan namuna'), ('contaminated', 'Ifloslangan namuna'), ('other', 'Boshqa sabab')], max_length=20, verbose_name='Rad sababi')),
                ('reject_note', models.TextField(blank=True, verbose_name='Rad izohi')),
                ('sample_taken_at', models.DateTimeField(blank=True, null=True, verbose_name='Namuna olingan vaqt')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Bajarilgan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_lab_items', to=settings.AUTH_USER_MODEL, verbose_name="Mas'ul laborant")),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='laboratory.laborder', verbose_name='Buyurtma')),
                ('patient_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_order_items', to='services.patientservice', verbose_name='Bemor xizmati')),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='laboratory.labresult', verbose_name='Natija')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='laboratory.labtemplate', verbose_name='Shablon')),
            ],
            options={
                'verbose_name': 'Buyurtma elementi',
                'verbose_name_plural': 'Buyurtma elementlari',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=20, verbose_name='Avvalgi holat')),
                ('to_status', models.CharField(max_length=20, verbose_name='Yangi holat')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name="O'zgartirilgan vaqt")),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Kim o'zgartirdi")),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='laboratory.laborderitem', verbose_name='Buyurtma elementi')),
            ],
            options={
                'verbose_name': 'Status log',
                'verbose_name_plural': 'Status loglar',
                'ordering': ['changed_at'],
            },
        ),
        migrations.CreateModel(
            name='LabTemplateService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_template_links', to='services.service', verbose_name='Xizmat')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_services', to='laboratory.labtemplate', verbose_name='Shablon')),
            ],
            options={
                'verbose_name': "Shablon-Xizmat bog'lanishi",
                'verbose_name_plural': "Shablon-Xizmat bog'lanishlari",
                'unique_together': {('template', 'service')},
            },
        ),
    ]
