# Generated by Django 5.2.12 on 2026-05-20 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_add_order_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborderitem',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='laboratory.labtemplate', verbose_name='Shablon'),
        ),
    ]
