# Generated by Django 5.2.12 on 2026-07-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DMEDSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookies_json', models.TextField(blank=True)),
                ('logged_in_at', models.DateTimeField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'DMED Session',
            },
        ),
        migrations.CreateModel(
            name='DMEDSyncRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('patient', 'Bemor kartasi'), ('visit', 'Qabul (statsionar/ambulator)'), ('patient_service', 'Bemor xizmati'), ('lab_result', 'Tahlil natijasi'), ('diagnostic', 'Diagnostika natijasi'), ('consultation', 'Konsultatsiya')], max_length=30, verbose_name='Entity turi')),
                ('entity_id', models.PositiveIntegerField(verbose_name='Entity ID')),
                ('entity_repr', models.CharField(blank=True, max_length=255, verbose_name='Tavsif')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('running', 'Jarayonda'), ('done', 'Bajarildi'), ('failed', 'Xato'), ('skipped', "O'tkazildi")], db_index=True, default='pending', max_length=10)),
                ('dmed_id', models.CharField(blank=True, max_length=100, verbose_name="DMED ID (muvaffaqiyatli bo'lsa)")),
                ('error', models.TextField(blank=True, verbose_name='Xato matni')),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('enqueued_at', models.DateTimeField(auto_now_add=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'DMED Sync yozuvi',
                'verbose_name_plural': 'DMED Sync yozuvlari',
                'ordering': ['-enqueued_at'],
                'indexes': [models.Index(fields=['status', 'enqueued_at'], name='dmed_sync_d_status_ea0b11_idx'), models.Index(fields=['entity_type', 'entity_id'], name='dmed_sync_d_entity__c3cc9a_idx')],
            },
        ),
    ]
