# Generated by Django 5.2.12 on 2026-07-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmed_sync', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dmedsession',
            name='cookies_json',
        ),
        migrations.AddField(
            model_name='dmedsession',
            name='last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dmedsession',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dmedsession',
            name='logged_in_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kim login qildi'),
        ),
        migrations.AddField(
            model_name='dmedsession',
            name='storage_state_json',
            field=models.TextField(blank=True, verbose_name='Storage state (cookies + localStorage)'),
        ),
    ]
