import os
"""
Django settings for conf project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(Path(__file__).resolve().parent.parent / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0n=^kv0l%nu2dq)+=@y!qdgzvoonh+n3x0cby61^1z(7n_6jb*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '164.92.130.93',
    'markaziyklinikkasalxona-statistika.uz',
    'www.markaziyklinikkasalxona-statistika.uz',
    'localhost',
    '127.0.0.1',
]
CSRF_FAILURE_VIEW = 'django.views.csrf.csrf_failure'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
    #my_apps
    'apps.statistic',
    'apps.patients',
    'apps.users',
    'apps.services',
    'apps.contracts',
    'apps.queue_app',
    'apps.laboratory',
    'apps.telegram_bot',
    'apps.care',
    'apps.billing',
    'apps.dmed_sync',
]

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL  = '/media/'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
}

# Telegram Bot
TELEGRAM_BOT_TOKEN  = os.environ.get('TELEGRAM_BOT_TOKEN', '')
TELEGRAM_BOT_SECRET = os.environ.get('TELEGRAM_BOT_SECRET', 'change-me-in-production')

# ── DMED RPA Sinxronizatsiya ──────────────────────────────────────────────────
DMED_SYNC_ENABLED   = os.environ.get('DMED_SYNC_ENABLED', 'True') == 'True'
DMED_URL            = os.environ.get('DMED_URL', '')       # https://dmed.uz
DMED_HEADLESS       = os.environ.get('DMED_HEADLESS', 'True') == 'True'
DMED_ALERT_CHAT_ID  = os.environ.get('DMED_ALERT_CHAT_ID', '')  # Telegram chat ID

# Entity turi → DMED rol nomi (rol tanlash sahifasidagi karta matni)
DMED_ROLE_MAP = {
    'patient':          'Menejer',    # Registrator → Menejer
    'visit':            'Menejer',
    'patient_service':  'Menejer',
    'lab_result':       'Laborant',
    'diagnostic':       'Shifokor',
    'consultation':     'Shifokor',
}

# visit_type → DMED appointments/create radio value
# 2073 = Kasalxona 🛏  |  1859 = Maslahatlar 🩺  |  2628 = Konsultatsiya
# 3096 = Diagnostika 🔬 |  1896 = Laboratoriya 🧪 |  265  = Xizmatlar ⚕️
# 2656 = Operatsiya 🛏️ |  3179 = Fizioterapiya 🚹 |  2703 = Tor mutaxassis 🏥
DMED_SERVICE_CATEGORY_MAP = {
    'inpatient':  '2073',  # Kasalxona
    'ambulatory': '1859',  # Maslahatlar
}

# Redis
REDIS_URL = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/0')

# Celery
CELERY_BROKER_URL         = REDIS_URL
CELERY_RESULT_BACKEND     = REDIS_URL
CELERY_TASK_SERIALIZER    = 'json'
CELERY_RESULT_SERIALIZER  = 'json'
CELERY_ACCEPT_CONTENT     = ['json']
CELERY_TIMEZONE           = 'Asia/Tashkent'
CELERY_BEAT_SCHEDULE = {
    'care-check-overdue-tasks': {
        'task': 'care.check_overdue_tasks',
        'schedule': 60.0,
    },
    'patients-send-due-schedule-reminders': {
        'task': 'patients.send_due_schedule_reminders',
        'schedule': 60.0,
    },
}

# Care (Hamshira) moduli
# Qancha vaqt 'delayed' holatda tursa, vazifa 'missed' deb belgilanadi (daqiqa)
CARE_TASK_MISSED_AFTER_MINUTES = int(os.environ.get('CARE_TASK_MISSED_AFTER_MINUTES', 120))

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'conf.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],   # ← shu qator bo'lishi shart
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'conf.wsgi.application'


# Database — .env da DB_ENGINE o'rnatilmasa SQLite (lokal dev), o'rnatilsa PostgreSQL (server)
_db_engine = os.getenv('DB_ENGINE', 'django.db.backends.sqlite3')

if _db_engine == 'django.db.backends.sqlite3':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': _db_engine,
            'NAME': os.getenv('DB_NAME', 'skb_stat'),
            'USER': os.getenv('DB_USER', 'skb_user'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

SITE_URL = 'https://markaziyklinikkasalxona-statistika.uz'
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/patients/'
LOGOUT_REDIRECT_URL = '/login/'
# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'uz'

LANGUAGES = [
    ('uz', "O'zbekcha"),
    ('ru', 'Русский'),
]

LOCALE_PATHS = [BASE_DIR / 'locale']

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

AUTH_USER_MODEL = 'users.CustomUser'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000

