# apps/patients/management/commands/load_locations.py

from django.core.management.base import BaseCommand
from apps.patients.models import Country, Region, District, City

class Command(BaseCommand):
    help = "O'zbekiston viloyatlari va tumanlarini yuklash"

    def handle(self, *args, **kwargs):
        # Davlat
        uz, _ = Country.objects.get_or_create(name="O'zbekiston")

        data = {
            "Toshkent shahri": {
                "Toshkent shahri": ["Bektemir", "Chilonzor", "Hamza", "Mirobod",
                                    "Mirzo Ulug'bek", "Sergeli", "Shayxontohur",
                                    "Olmazor", "Uchtepa", "Yakkasaroy", "Yunusobod",
                                    "Yashnobod"]
            },
            "Toshkent viloyati": {
                "Toshkent tumani": ["Yangiyo'l", "Qibray", "Bo'ka", "Oqqo'rg'on"],
                "Bekobod": ["Bekobod shahri", "Yangiobod"],
                "Bo'stonliq": ["G'azalkent", "Chorvoq"],
                "Chirchiq": ["Chirchiq shahri"],
                "Ohangaron": ["Ohangaron shahri", "Olmaliq"],
                "Zangiota": ["Urluk", "Eski Toshkent"],
                "Quyichirchiq": ["Toytepa"],
                "Yuqorichirchiq": ["Xo'jakent"],
                "Parkent": ["Parkent shahri"],
                "Piskent": ["Piskent shahri"],
            },
            "Samarqand viloyati": {
                "Samarqand shahri": ["Samarqand"],
                "Bulung'ur": ["Bulung'ur"],
                "Ishtixon": ["Ishtixon"],
                "Jomboy": ["Jomboy"],
                "Kattaqo'rg'on": ["Kattaqo'rg'on"],
                "Narpay": ["Narpay"],
                "Nurobod": ["Nurobod"],
                "Oqdaryo": ["Oqdaryo"],
                "Payariq": ["Payariq"],
                "Pastdarg'om": ["Pastdarg'om"],
                "Paxtachi": ["Paxtachi"],
                "Qo'shrabot": ["Qo'shrabot"],
                "Toyloq": ["Toyloq"],
                "Urgut": ["Urgut"],
            },
            "Farg'ona viloyati": {
                "Farg'ona shahri": ["Farg'ona"],
                "Oltiariq": ["Oltiariq"],
                "Bag'dod": ["Bag'dod"],
                "Beshariq": ["Beshariq"],
                "Buvayda": ["Buvayda"],
                "Dang'ara": ["Dang'ara"],
                "Furqat": ["Furqat"],
                "Qo'qon": ["Qo'qon shahri"],
                "Marg'ilon": ["Marg'ilon shahri"],
                "Quva": ["Quva"],
                "Rishton": ["Rishton"],
                "So'x": ["So'x"],
                "Toshloq": ["Toshloq"],
                "Uchko'prik": ["Uchko'prik"],
                "O'zbekiston": ["O'zbekiston"],
                "Yozyovon": ["Yozyovon"],
            },
            "Andijon viloyati": {
                "Andijon shahri": ["Andijon"],
                "Asaka": ["Asaka"],
                "Baliqchi": ["Baliqchi"],
                "Bo'ston": ["Bo'ston"],
                "Buloqboshi": ["Buloqboshi"],
                "Izboskan": ["Izboskan"],
                "Jalolquduq": ["Jalolquduq"],
                "Xo'jaobod": ["Xo'jaobod"],
                "Qo'rg'ontepa": ["Qo'rg'ontepa"],
                "Marhamat": ["Marhamat"],
                "Oltinko'l": ["Oltinko'l"],
                "Paxtaobod": ["Paxtaobod"],
                "Shahrixon": ["Shahrixon"],
                "Ulug'nor": ["Ulug'nor"],
            },
            "Namangan viloyati": {
                "Namangan shahri": ["Namangan"],
                "Chortoq": ["Chortoq"],
                "Chust": ["Chust"],
                "Kosonsoy": ["Kosonsoy"],
                "Mingbuloq": ["Mingbuloq"],
                "Norin": ["Norin"],
                "Pop": ["Pop"],
                "To'raqo'rg'on": ["To'raqo'rg'on"],
                "Uychi": ["Uychi"],
                "Yangiqo'rg'on": ["Yangiqo'rg'on"],
            },
            "Buxoro viloyati": {
                "Buxoro shahri": ["Buxoro"],
                "Vobkent": ["Vobkent"],
                "G'ijduvon": ["G'ijduvon"],
                "Jondor": ["Jondor"],
                "Kogon": ["Kogon"],
                "Olot": ["Olot"],
                "Peshku": ["Peshku"],
                "Qorako'l": ["Qorako'l"],
                "Qorovulbozor": ["Qorovulbozor"],
                "Romitan": ["Romitan"],
                "Shofirkon": ["Shofirkon"],
            },
            "Xorazm viloyati": {
                "Urganch shahri": ["Urganch"],
                "Bog'ot": ["Bog'ot"],
                "Gurlan": ["Gurlan"],
                "Xiva": ["Xiva"],
                "Xonqa": ["Xonqa"],
                "Hazorasp": ["Hazorasp"],
                "Qo'shko'pir": ["Qo'shko'pir"],
                "Shovot": ["Shovot"],
                "Tuproqqal'a": ["Tuproqqal'a"],
                "Yangiariq": ["Yangiariq"],
                "Yangibozor": ["Yangibozor"],
            },
            "Qashqadaryo viloyati": {
                "Qarshi shahri": ["Qarshi"],
                "Chiroqchi": ["Chiroqchi"],
                "Dehqonobod": ["Dehqonobod"],
                "G'uzor": ["G'uzor"],
                "Kasbi": ["Kasbi"],
                "Kitob": ["Kitob"],
                "Koson": ["Koson"],
                "Mirishkor": ["Mirishkor"],
                "Muborak": ["Muborak"],
                "Nishon": ["Nishon"],
                "Qamashi": ["Qamashi"],
                "Shahrisabz": ["Shahrisabz"],
                "Yakkabog'": ["Yakkabog'"],
            },
            "Surxondaryo viloyati": {
                "Termiz shahri": ["Termiz"],
                "Angor": ["Angor"],
                "Bandixon": ["Bandixon"],
                "Boysun": ["Boysun"],
                "Denov": ["Denov"],
                "Jarqo'rg'on": ["Jarqo'rg'on"],
                "Muzrabot": ["Muzrabot"],
                "Oltinsoy": ["Oltinsoy"],
                "Qiziriq": ["Qiziriq"],
                "Qumqo'rg'on": ["Qumqo'rg'on"],
                "Sariosiyo": ["Sariosiyo"],
                "Sherobod": ["Sherobod"],
                "Shurchi": ["Shurchi"],
                "Uzun": ["Uzun"],
            },
            "Jizzax viloyati": {
                "Jizzax shahri": ["Jizzax"],
                "Arnasoy": ["Arnasoy"],
                "Baxmal": ["Baxmal"],
                "Do'stlik": ["Do'stlik"],
                "Forish": ["Forish"],
                "G'allaorol": ["G'allaorol"],
                "Mirzacho'l": ["Mirzacho'l"],
                "Paxtakor": ["Paxtakor"],
                "Yangiobod": ["Yangiobod"],
                "Zarbdor": ["Zarbdor"],
                "Zafarobod": ["Zafarobod"],
                "Zomin": ["Zomin"],
            },
            "Sirdaryo viloyati": {
                "Guliston shahri": ["Guliston"],
                "Boyovut": ["Boyovut"],
                "Gurushli": ["Gurushli"],
                "Xavos": ["Xavos"],
                "Mirzaobod": ["Mirzaobod"],
                "Oqoltin": ["Oqoltin"],
                "Sardoba": ["Sardoba"],
                "Sayxunobod": ["Sayxunobod"],
                "Sirdaryо": ["Sirdaryo"],
            },
            "Navoiy viloyati": {
                "Navoiy shahri": ["Navoiy"],
                "Karmana": ["Karmana"],
                "Konimex": ["Konimex"],
                "Navbahor": ["Navbahor"],
                "Nurota": ["Nurota"],
                "Qiziltepa": ["Qiziltepa"],
                "Tomdi": ["Tomdi"],
                "Uchquduq": ["Uchquduq"],
                "Xatirchi": ["Xatirchi"],
            },
            "Qoraqalpog'iston": {
                "Nukus shahri": ["Nukus"],
                "Amudaryo": ["Amudaryo"],
                "Beruniy": ["Beruniy"],
                "Bo'zatov": ["Bo'zatov"],
                "Chimboy": ["Chimboy"],
                "Ellikkala": ["Ellikkala"],
                "Kegeyli": ["Kegeyli"],
                "Mo'ynoq": ["Mo'ynoq"],
                "Qanliko'l": ["Qanliko'l"],
                "Qorao'zak": ["Qorao'zak"],
                "Qo'ng'irot": ["Qo'ng'irot"],
                "Shumanay": ["Shumanay"],
                "Taxtako'pir": ["Taxtako'pir"],
                "To'rtko'l": ["To'rtko'l"],
                "Xo'jayli": ["Xo'jayli"],
            },
        }

        total = 0
        for region_name, districts in data.items():
            region, _ = Region.objects.get_or_create(country=uz, name=region_name)
            for district_name, cities in districts.items():
                district, _ = District.objects.get_or_create(region=region, name=district_name)
                for city_name in cities:
                    City.objects.get_or_create(district=district, name=city_name)
                    total += 1

        self.stdout.write(self.style.SUCCESS(f"Muvaffaqiyatli yuklandi!"))