# Generated by Django 5.2.12 on 2026-06-15 05:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('patients', '0028_consultationrequest_consultationresponse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('action', models.CharField(choices=[('created', 'Yaratildi'), ('updated', 'Yangilandi'), ('status_changed', "Holat o'zgardi"), ('resolved', 'Hal qilindi'), ('deleted', "O'chirildi")], max_length=20, verbose_name='Amal')),
                ('field_name', models.CharField(blank=True, max_length=100, verbose_name='Maydon')),
                ('old_value', models.TextField(blank=True, verbose_name='Eski qiymat')),
                ('new_value', models.TextField(blank=True, verbose_name='Yangi qiymat')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Bajardi')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('patient_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_audit_logs', to='patients.patientcard', verbose_name='Bemor kartasi')),
            ],
            options={
                'verbose_name': 'Audit log',
                'verbose_name_plural': 'Audit loglar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('condition_worsened', 'Bemorning ahvoli yomonlashdi'), ('allergic_reaction', 'Allergik reaksiya'), ('bp_change', "Qon bosimi keskin o'zgardi"), ('fainting', 'Hushdan ketish'), ('respiratory_failure', 'Nafas yetishmovchiligi'), ('other', 'Boshqa')], max_length=25, verbose_name='Holat turi')),
                ('description', models.TextField(blank=True, verbose_name='Tasvir')),
                ('status', models.CharField(choices=[('open', 'Ochiq'), ('acknowledged', 'Qabul qilindi'), ('resolved', 'Hal qilindi')], default='open', max_length=15, verbose_name='Holati')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuz bergan vaqt')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Hal qilingan vaqt')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_events', to='patients.department', verbose_name="Bo'lim")),
                ('notified_doctors', models.ManyToManyField(blank=True, related_name='emergency_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Xabar berilgan shifokorlar')),
                ('notified_head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_head_notifications', to=settings.AUTH_USER_MODEL, verbose_name="Xabar berilgan bo'lim mudiri")),
                ('patient_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_events', to='patients.patientcard', verbose_name='Bemor kartasi')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_emergencies', to=settings.AUTH_USER_MODEL, verbose_name='Xabar bergan hamshira')),
            ],
            options={
                'verbose_name': 'Favqulodda holat',
                'verbose_name_plural': 'Favqulodda holatlar',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=255, verbose_name='Dori nomi')),
                ('medicine_type', models.CharField(choices=[('tablet', 'Tabletka'), ('capsule', 'Kapsula'), ('injection', 'Ukol'), ('drops', 'Tomchi'), ('ointment', 'Maz'), ('system', 'Sistema'), ('other', 'Boshqa')], default='tablet', max_length=15, verbose_name='Dori turi')),
                ('duration_days', models.PositiveIntegerField(verbose_name='Davolash davomiyligi (kun)')),
                ('times_per_day', models.PositiveSmallIntegerField(verbose_name='Kuniga necha marta')),
                ('administration_times', models.JSONField(default=list, help_text='["08:00", "14:00", "20:00"]', verbose_name='Qabul qilish vaqtlari')),
                ('food_relation', models.CharField(choices=[('before_meal', 'Ovqatdan oldin'), ('with_meal', 'Ovqat paytida'), ('after_meal', 'Ovqatdan keyin'), ('none', "Farqi yo'q")], default='none', max_length=15, verbose_name="Ovqat bilan bog'liqligi")),
                ('single_dose', models.CharField(blank=True, max_length=100, verbose_name='Bir martalik doza')),
                ('max_daily_dose', models.CharField(blank=True, max_length=100, verbose_name='Maksimal sutkalik doza')),
                ('special_instructions', models.TextField(blank=True, verbose_name="Maxsus ko'rsatmalar")),
                ('doctor_comment', models.TextField(blank=True, verbose_name='Shifokor izohi')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Boshlanish sanasi')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('completed', 'Yakunlangan'), ('cancelled', 'Bekor qilingan')], default='active', max_length=15, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_medication_orders', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
                ('patient_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_orders', to='patients.patientcard', verbose_name='Bemor kartasi')),
                ('prescribed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_medications', to='patients.doctor', verbose_name='Tayinlagan shifokor')),
            ],
            options={
                'verbose_name': 'Dori/muolaja tayinlash',
                'verbose_name_plural': 'Dori/muolaja tayinlashlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('referral', "Yo'llanma"), ('medication', 'Dori-muolaja'), ('task_due', 'Vazifa vaqti yetdi'), ('task_delayed', 'Vazifa kechikdi'), ('task_missed', "Vazifa o'tkazib yuborildi"), ('emergency', 'Favqulodda holat'), ('other', 'Boshqa')], default='other', max_length=20, verbose_name='Turi')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('message', models.TextField(blank=True, verbose_name='Xabar')),
                ('priority', models.CharField(choices=[('normal', 'Oddiy'), ('urgent', 'Shoshilinch')], default='normal', max_length=10, verbose_name='Ustuvorlik')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('patient_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='care_notifications', to='patients.patientcard', verbose_name='Bemor kartasi')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='care_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Qabul qiluvchi')),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NurseTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('medication', 'Dori berish'), ('injection', 'Ukol qilish'), ('consultation', 'Konsultatsiya'), ('diagnostic', 'Diagnostik tekshiruv'), ('lab', 'Laboratoriya tekshiruvi'), ('procedure', 'Muolaja'), ('other', 'Boshqa')], max_length=15, verbose_name='Vazifa turi')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('scheduled_at', models.DateTimeField(verbose_name='Bajarish vaqti')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('done', 'Bajarildi'), ('delayed', 'Kechiktirildi'), ('cancelled', 'Bekor qilindi'), ('missed', "O'tkazib yuborildi")], default='pending', max_length=10, verbose_name='Holati')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('delay_reason', models.CharField(blank=True, choices=[('patient_absent', "Bemor yo'q edi"), ('patient_refused', 'Bemor rad etdi'), ('condition_worsened', "Bemorning ahvoli og'irlashdi"), ('medicine_unavailable', 'Dori mavjud emas'), ('device_broken', 'Qurilma nosoz'), ('other', 'Boshqa sabab')], max_length=25, verbose_name='Kechikish sababi')),
                ('delayed_at', models.DateTimeField(blank=True, null=True, verbose_name='Kechikkan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('patient_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_tasks', to='patients.patientcard', verbose_name='Bemor kartasi')),
            ],
            options={
                'verbose_name': 'Hamshira vazifasi',
                'verbose_name_plural': 'Hamshira vazifalari',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('consultation', 'Konsultatsiya'), ('diagnostic', 'Diagnostik tekshiruv'), ('lab', 'Laboratoriya tekshiruvi'), ('treatment', 'Muolaja'), ('other', 'Boshqa xizmatlar')], max_length=20, verbose_name='Xizmat turi')),
                ('service_detail', models.CharField(blank=True, max_length=255, verbose_name='Xizmat tafsiloti')),
                ('priority', models.CharField(choices=[('normal', 'Oddiy'), ('urgent', 'Shoshilinch'), ('critical', 'Juda shoshilinch')], default='normal', max_length=10, verbose_name='Ustuvorlik')),
                ('scheduled_at', models.DateTimeField(verbose_name='Qabul sanasi va vaqti')),
                ('comment', models.TextField(blank=True, verbose_name='Izoh')),
                ('status', models.CharField(choices=[('sent', 'Yuborildi'), ('in_progress', 'Bajarilmoqda'), ('done', 'Bajarildi'), ('cancelled', 'Bekor qilindi')], default='sent', max_length=15, verbose_name='Holati')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_referrals', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
                ('patient_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='patients.patientcard', verbose_name='Bemor kartasi')),
                ('referring_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_referrals', to='patients.doctor', verbose_name="Yo'llanma bergan shifokor")),
                ('target_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_referrals', to='patients.doctor', verbose_name='Tanlangan shifokor')),
            ],
            options={
                'verbose_name': "Yo'llanma",
                'verbose_name_plural': "Yo'llanmalar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskCompletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='Bajarilgan vaqt')),
                ('action', models.CharField(choices=[('done', 'Bajarildi'), ('delayed', 'Kechiktirildi'), ('cancelled', 'Bekor qilindi'), ('missed', "O'tkazib yuborildi")], max_length=10, verbose_name='Amal')),
                ('comment', models.CharField(blank=True, max_length=500, verbose_name='Izoh')),
                ('delay_reason', models.CharField(blank=True, choices=[('patient_absent', "Bemor yo'q edi"), ('patient_refused', 'Bemor rad etdi'), ('condition_worsened', "Bemorning ahvoli og'irlashdi"), ('medicine_unavailable', 'Dori mavjud emas'), ('device_broken', 'Qurilma nosoz'), ('other', 'Boshqa sabab')], max_length=25, verbose_name='Kechikish sababi')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_completion_logs', to=settings.AUTH_USER_MODEL, verbose_name='Bajaruvchi')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_logs', to='care.nursetask', verbose_name='Vazifa')),
            ],
            options={
                'verbose_name': 'Vazifa bajarilish logi',
                'verbose_name_plural': 'Vazifa bajarilish loglari',
                'ordering': ['-performed_at'],
            },
        ),
    ]
