# Generated by Django 5.2.12 on 2026-06-29 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0001_initial'),
        ('patients', '0045_ambulatoryconsultation_doctor_v2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationorder',
            name='prescribed_by_v2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_medications', to=settings.AUTH_USER_MODEL, verbose_name='Tayinlagan shifokor'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referring_doctor_v2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_referrals', to=settings.AUTH_USER_MODEL, verbose_name="Yo'llanma bergan shifokor"),
        ),
        migrations.AddField(
            model_name='referral',
            name='target_doctor_v2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_referrals', to=settings.AUTH_USER_MODEL, verbose_name='Tanlangan shifokor'),
        ),
        migrations.AlterField(
            model_name='medicationorder',
            name='prescribed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_medications_old', to='patients.doctor', verbose_name='Tayinlagan shifokor'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referring_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_referrals_old', to='patients.doctor', verbose_name="Yo'llanma bergan shifokor"),
        ),
        migrations.AlterField(
            model_name='referral',
            name='target_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_referrals_old', to='patients.doctor', verbose_name='Tanlangan shifokor'),
        ),
    ]
