# Generated by Django 5.2.12 on 2026-03-24 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_patientcard_registered_by_patientcard_status'),
        ('users', '0002_alter_customuser_options_alter_customuser_department_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.department'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('doctor', 'Shifokor'), ('statistician', 'Statistik'), ('reception', 'Qabulxona'), ('viewer', "Faqat ko'rish")], default='viewer', max_length=20),
        ),
    ]
