# Generated by Django 5.2.12 on 2026-06-02 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0021_add_transfer_date_to_patient_transfer'),
        ('users', '0005_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='staff_users', to='patients.department', verbose_name="Bo'limlar"),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.department', verbose_name="Asosiy bo'lim"),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('doctor', 'Shifokor'), ('statistician', 'Statistik'), ('reception', 'Qabulxona'), ('laborant', 'Laborant'), ('viewer', "Faqat ko'rish")], default='viewer', max_length=20),
        ),
    ]
