# Generated by Django 5.2.12 on 2026-06-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('doctor', 'Shifokor'), ('statistician', 'Statistik'), ('reception', 'Qabulxona'), ('laborant', 'Laborant'), ('nurse', 'Hamshira'), ('head_nurse', 'Katta hamshira'), ('diagnostician', 'Diagnost'), ('viewer', "Faqat ko'rish"), ('old', 'old')], default='viewer', max_length=20),
        ),
    ]
