# Generated by Django 5.2.12 on 2026-06-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_general_practitioner',
            field=models.BooleanField(default=False, verbose_name="Terapevt (barcha bemorlarga dastlabki ko'rik)"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_head',
            field=models.BooleanField(default=False, verbose_name="Bo'lim mudiri"),
        ),
    ]
