# Generated by Django 5.2.12 on 2026-03-17 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ICD10Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('title_uz', models.CharField(max_length=500)),
                ('title_ru', models.CharField(blank=True, max_length=500)),
                ('category', models.CharField(blank=True, max_length=5)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('is_head', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.department')),
            ],
        ),
        migrations.CreateModel(
            name='PatientCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_record_number', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Erkak'), ('F', 'Ayol')], max_length=1)),
                ('birth_date', models.DateField()),
                ('address', models.TextField()),
                ('social_status', models.CharField(choices=[('employed', 'Ishlaydi'), ('student_higher', 'Student'), ('student_school', "O'quvchi"), ('unemployed', 'Ishlamaydi')], max_length=20)),
                ('passport_serial', models.CharField(max_length=9)),
                ('referral_type', models.CharField(choices=[('self', "O'zi kelgan"), ('ambulance', 'Tez tibbiy yordam'), ('referral', "Yo'llanma orqali")], max_length=20)),
                ('referring_diagnosis', models.TextField(blank=True)),
                ('admission_diagnosis', models.TextField(blank=True)),
                ('hours_after_illness', models.CharField(choices=[('under_6', 'Dastlabki 6 soat ichida'), ('7_to_24', '7-24 soat ichida'), ('over_24', '24 soatdan keyin')], max_length=10)),
                ('is_emergency', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('admission_date', models.DateTimeField()),
                ('admission_count', models.CharField(choices=[('first', 'Birinchi marta'), ('repeated', 'Qayta')], max_length=10)),
                ('days_in_hospital', models.PositiveIntegerField()),
                ('outcome', models.CharField(choices=[('discharged', 'Chiqarildi'), ('deceased', 'Vafot etdi'), ('transferred', "Boshqa shifoxonaga o'tkazildi")], max_length=15)),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('clinical_main_diagnosis', models.CharField(blank=True, help_text='MKB-10 kodi', max_length=20)),
                ('clinical_main_diagnosis_text', models.TextField(blank=True)),
                ('clinical_comorbidities', models.TextField(blank=True)),
                ('pathological_main_diagnosis', models.CharField(blank=True, help_text='MKB-10 kodi', max_length=20)),
                ('pathological_main_diagnosis_text', models.TextField(blank=True)),
                ('pathological_comorbidities', models.TextField(blank=True)),
                ('aids_test_date', models.DateField(blank=True, null=True)),
                ('aids_test_result', models.CharField(blank=True, max_length=50)),
                ('wp_test_date', models.DateField(blank=True, null=True)),
                ('wp_test_result', models.CharField(blank=True, max_length=50)),
                ('is_war_veteran', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attending_doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attending_cards', to='patients.doctor')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='patients.department')),
                ('department_head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_cards', to='patients.doctor')),
                ('referral_organization', models.ForeignKey(blank=True, help_text="Faqat yo'llanma orqali kelganda", null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.organization')),
            ],
        ),
        migrations.CreateModel(
            name='DeathCause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immediate_cause', models.TextField()),
                ('underlying_cause', models.TextField()),
                ('main_disease_code', models.CharField(max_length=20)),
                ('other_significant_conditions', models.TextField(blank=True)),
                ('patient_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='death_cause', to='patients.patientcard')),
            ],
        ),
        migrations.CreateModel(
            name='SurgicalOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_date', models.DateField()),
                ('operation_name', models.CharField(max_length=255)),
                ('complication', models.TextField(blank=True)),
                ('patient_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='patients.patientcard')),
            ],
        ),
    ]
