# Generated by Django 5.2.12 on 2026-03-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_city_country_district_remove_patientcard_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcard',
            name='referral_type',
            field=models.CharField(choices=[('self', "O'zi kelgan"), ('ambulance', 'Tez tibbiy yordam'), ('referral', "Yo'llanma orqali"), ('liniya', 'Liniya')], max_length=20),
        ),
    ]
