# Generated by Django 5.2.12 on 2026-03-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patientcard_referral_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcard',
            name='resident_status',
            field=models.CharField(choices=[('resident', 'Rezident'), ('non_resident', 'Norezident')], default='resident', max_length=15),
        ),
    ]
