# Generated by Django 5.2.12 on 2026-03-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patientcard_resident_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcard',
            name='passport_serial',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
