# Generated by Django 5.2.12 on 2026-03-18 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patientcard_passport_serial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargeConclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Chiqish xulosasi',
                'verbose_name_plural': 'Chiqish xulosalari',
            },
        ),
        migrations.AddField(
            model_name='patientcard',
            name='discharge_conclusion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.dischargeconclusion', verbose_name='Chiqish xulosasi'),
        ),
    ]
