# Generated by Django 5.2.12 on 2026-03-18 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_dischargeconclusion_patientcard_discharge_conclusion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Shahar', 'verbose_name_plural': 'Shaharlar'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Davlat', 'verbose_name_plural': 'Davlatlar'},
        ),
        migrations.AlterModelOptions(
            name='deathcause',
            options={'verbose_name': "O'lim sababi", 'verbose_name_plural': "O'lim sabablari"},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': "Bo'lim", 'verbose_name_plural': "Bo'limlar"},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'Tuman', 'verbose_name_plural': 'Tumanlar'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Shifokor', 'verbose_name_plural': 'Shifokorlar'},
        ),
        migrations.AlterModelOptions(
            name='icd10code',
            options={'ordering': ['code'], 'verbose_name': 'MKB-10 kodi', 'verbose_name_plural': 'MKB-10 kodlari'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Muassasa', 'verbose_name_plural': 'Muassasalar'},
        ),
        migrations.AlterModelOptions(
            name='patientcard',
            options={'ordering': ['-admission_date'], 'verbose_name': 'Bemor kartasi', 'verbose_name_plural': 'Bemor kartalari'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Viloyat', 'verbose_name_plural': 'Viloyatlar'},
        ),
        migrations.AlterModelOptions(
            name='surgicaloperation',
            options={'verbose_name': 'Jarrohlik amaliyoti', 'verbose_name_plural': 'Jarrohlik amaliyotlari'},
        ),
        migrations.AlterModelOptions(
            name='village',
            options={'verbose_name': 'Qishloq', 'verbose_name_plural': 'Qishloqlar'},
        ),
        migrations.AlterField(
            model_name='deathcause',
            name='immediate_cause',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='deathcause',
            name='main_disease_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='deathcause',
            name='underlying_cause',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patientcard',
            name='attending_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attending_cards', to='patients.doctor'),
        ),
        migrations.AlterField(
            model_name='patientcard',
            name='clinical_main_diagnosis',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='patientcard',
            name='days_in_hospital',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientcard',
            name='department_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_cards', to='patients.doctor'),
        ),
        migrations.AlterField(
            model_name='patientcard',
            name='pathological_main_diagnosis',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='patientcard',
            name='referral_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.organization'),
        ),
        migrations.AlterField(
            model_name='patientcard',
            name='street_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='surgicaloperation',
            name='operation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surgicaloperation',
            name='operation_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
