# Generated by Django 5.2.12 on 2026-03-19 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_alter_city_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Amaliyot turi',
                'verbose_name_plural': 'Amaliyot turlari',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='surgicaloperation',
            name='anesthesia',
            field=models.CharField(blank=True, choices=[('yes', 'Narkoz bilan'), ('no', 'Narkozsiz'), ('local', 'Mahalliy narkoz')], max_length=10),
        ),
        migrations.AddField(
            model_name='surgicaloperation',
            name='operation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.operationtype', verbose_name='Amaliyot turi'),
        ),
    ]
