# Generated by Django 5.2.12 on 2026-03-23 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_operationtype_surgicaloperation_anesthesia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Shifoxona turi',
                'verbose_name_plural': 'Shifoxona turlari',
            },
        ),
        migrations.AddField(
            model_name='patientcard',
            name='JSHSHIR',
            field=models.CharField(blank=True, max_length=14, verbose_name='JSHSHIR'),
        ),
        migrations.AddField(
            model_name='patientcard',
            name='patient_category',
            field=models.CharField(choices=[('railway', "Temir yo'lchi"), ('paid', 'Pullik'), ('non_resident', 'Norezident'), ('foreign', 'Chet el fuqarosi')], default='railway', max_length=15, verbose_name='Bemor kategoriyasi'),
        ),
        migrations.AddField(
            model_name='patientcard',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefon raqami'),
        ),
        migrations.AddField(
            model_name='patientcard',
            name='position',
            field=models.CharField(blank=True, max_length=255, verbose_name='Lavozimi'),
        ),
        migrations.AddField(
            model_name='patientcard',
            name='workplace',
            field=models.CharField(blank=True, max_length=255, verbose_name="Ish joyi / O'quv joyi"),
        ),
        migrations.AlterField(
            model_name='patientcard',
            name='admission_count',
            field=models.CharField(blank=True, choices=[('first', 'Birinchi marta'), ('repeated', 'Qayta')], max_length=10),
        ),
        migrations.AlterField(
            model_name='patientcard',
            name='hours_after_illness',
            field=models.CharField(blank=True, choices=[('under_6', 'Dastlabki 6 soat ichida'), ('7_to_24', '7-24 soat ichida'), ('over_24', '24 soatdan keyin')], max_length=10),
        ),
        migrations.AlterField(
            model_name='patientcard',
            name='outcome',
            field=models.CharField(blank=True, choices=[('discharged', 'Chiqarildi'), ('deceased', 'Vafot etdi'), ('transferred', "Boshqa shifoxonaga o'tkazildi")], max_length=15),
        ),
        migrations.AlterField(
            model_name='patientcard',
            name='referral_type',
            field=models.CharField(blank=True, choices=[('self', "O'zi kelgan"), ('ambulance', 'Tez tibbiy yordam'), ('referral', "Yo'llanma orqali"), ('liniya', 'Liniya')], max_length=20),
        ),
        migrations.AlterField(
            model_name='patientcard',
            name='social_status',
            field=models.CharField(blank=True, choices=[('employed', 'Ishlaydi'), ('unemployed', 'Vaqtincha ishsiz'), ('student_higher', 'Student'), ('student_school', "O'quvchi"), ('dependent', "Ota-ona qaramog'ida")], max_length=20),
        ),
        migrations.AddField(
            model_name='patientcard',
            name='hospital_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.hospitaltype', verbose_name='Shifoxona turi'),
        ),
    ]
