# Generated by Django 5.2.12 on 2026-03-24 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_hospitaltype_patientcard_jshshir_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcard',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_patients', to=settings.AUTH_USER_MODEL, verbose_name='Registratsiya qilgan'),
        ),
        migrations.AddField(
            model_name='patientcard',
            name='status',
            field=models.CharField(choices=[('registered', 'Registratsiya qilingan'), ('admitted', 'Yotqizilgan'), ('completed', 'Yakunlangan')], default='registered', max_length=15, verbose_name='Bemor statusi'),
        ),
    ]
