# Generated by Django 5.2.12 on 2026-03-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_patientcard_registered_by_patientcard_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcard',
            name='is_pensioner',
            field=models.BooleanField(default=False, verbose_name='Pensioner'),
        ),
        migrations.AlterField(
            model_name='patientcard',
            name='social_status',
            field=models.CharField(blank=True, choices=[('employed', 'Ishlaydi'), ('unemployed', 'Vaqtincha ishsiz'), ('pensioner', 'Pensioner'), ('student_higher', 'Student'), ('student_school', "O'quvchi"), ('dependent', "Ota-ona qaramog'ida")], max_length=20),
        ),
    ]
