# Generated by Django 5.2.12 on 2026-03-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_patientcard_is_pensioner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcard',
            name='patient_category',
            field=models.CharField(choices=[('railway', "Temir yo'lchi"), ('paid', 'Pullik'), ('non_resident', 'Norezident')], default='railway', max_length=15, verbose_name='Bemor kategoriyasi'),
        ),
    ]
