# Generated by Django 5.2.12 on 2026-03-31 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_alter_patientcard_patient_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['enterprise_name', 'branch_name'], 'verbose_name': 'Muassasa', 'verbose_name_plural': 'Muassasalar'},
        ),
        migrations.RemoveField(
            model_name='organization',
            name='name',
        ),
        migrations.AddField(
            model_name='organization',
            name='branch_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Filial kodi'),
        ),
        migrations.AddField(
            model_name='organization',
            name='branch_name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Filial nomi'),
        ),
        migrations.AddField(
            model_name='organization',
            name='enterprise_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Korxona kodi'),
        ),
        migrations.AddField(
            model_name='organization',
            name='enterprise_inn',
            field=models.CharField(blank=True, max_length=20, verbose_name='Korxona INN'),
        ),
        migrations.AddField(
            model_name='organization',
            name='enterprise_name',
            field=models.CharField(default='', max_length=500, verbose_name='Korxona nomi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientcard',
            name='workplace_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='patients.organization', verbose_name="Ish joyi (ro'yxatdan)"),
        ),
    ]
