# Generated by Django 5.2.12 on 2026-04-03 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_alter_organization_options_remove_organization_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transferred_at', models.DateTimeField(auto_now_add=True, verbose_name="Ko'chirish sanasi")),
                ('reason', models.TextField(blank=True, verbose_name='Sabab')),
                ('from_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='patients.department', verbose_name='Qayerdan')),
                ('patient_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='patients.patientcard', verbose_name='Bemor kartasi')),
                ('to_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to='patients.department', verbose_name='Qayerga')),
                ('transferred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Kim ko'chirgan")),
            ],
            options={
                'verbose_name': "Bo'lim ko'chirish",
                'verbose_name_plural': "Bo'lim ko'chirishlar",
                'ordering': ['-transferred_at'],
            },
        ),
    ]
