# Generated by Django 5.2.12 on 2026-04-09 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_patientcard_parent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcard',
            name='visit_type',
            field=models.CharField(blank=True, choices=[('inpatient', 'Statsionar (yotqizilgan)'), ('ambulatory', 'Ambulator (kunlik)')], default='inpatient', max_length=15, verbose_name='Tashrif turi'),
        ),
    ]
