# Generated by Django 5.2.12 on 2026-05-10 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0017_alter_patientcard_visit_type'),
        ('patients', '0018_patienttransfer'),
    ]

    operations = [
    ]
