# Generated by Django 5.2.12 on 2026-05-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0019_merge_20260511_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienttransfer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
