# Generated by Django 5.2.12 on 2026-05-19 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0020_alter_patienttransfer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttransfer',
            name='transfer_date',
            field=models.DateField(blank=True, null=True, verbose_name="Ko'chirish sanasi"),
        ),
        migrations.AlterField(
            model_name='patienttransfer',
            name='transferred_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
    ]
