# Generated by Django 5.2.12 on 2026-06-08 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0025_exam_epicrisis_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Tizim foydalanuvchisi'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='is_head',
            field=models.BooleanField(default=False, verbose_name="Bo'lim mudiri"),
        ),
        migrations.CreateModel(
            name='DoctorNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255, verbose_name='Xabar')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_notifications', to='patients.patientcard')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Qabul qiluvchi')),
            ],
            options={
                'verbose_name': 'Shifokor bildirishnomasi',
                'verbose_name_plural': 'Shifokor bildirishnomalari',
                'ordering': ['-created_at'],
            },
        ),
    ]
