# Generated by Django 5.2.12 on 2026-06-08 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0026_doctor_user_alter_doctor_is_head_doctornotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=255, verbose_name='Dori vositasi nomi')),
                ('dosage', models.CharField(blank=True, max_length=100, verbose_name='Dori dozasi')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Muolaja soni')),
                ('schedule_note', models.CharField(blank=True, max_length=255, verbose_name='Bajarish vaqti')),
                ('medicine_source', models.CharField(choices=[('patient_brought', 'Bemor tomonidan olib kelingan'), ('clinic_stock', 'Klinika omboridan')], default='clinic_stock', max_length=20, verbose_name='Dori manbasi')),
                ('status', models.CharField(choices=[('assigned', 'Tayinlangan'), ('in_progress', 'Jarayonda'), ('done', 'Bajarilgan'), ('cancelled', 'Bekor qilingan')], default='assigned', max_length=15, verbose_name='Holati')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tayinlangan sana')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_procedures', to='patients.doctor', verbose_name='Tayinlagan shifokor')),
                ('patient_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_procedures', to='patients.patientcard', verbose_name='Bemor kartasi')),
            ],
            options={
                'verbose_name': 'Tibbiy muolaja',
                'verbose_name_plural': 'Tibbiy muolajalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='Bajarilgan vaqt')),
                ('comment', models.CharField(blank=True, max_length=500, verbose_name='Izoh')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_procedures', to=settings.AUTH_USER_MODEL, verbose_name='Bajaruvchi hamshira')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='patients.treatmentprocedure', verbose_name='Muolaja')),
            ],
            options={
                'verbose_name': 'Muolaja bajarilish logi',
                'verbose_name_plural': 'Muolaja bajarilish loglari',
                'ordering': ['-performed_at'],
            },
        ),
    ]
