# Generated by Django 5.2.12 on 2026-06-08 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0027_treatmentprocedure_procedureexecutionlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(choices=[('neurology', 'Nevrologiya'), ('cardiology', 'Kardiologiya'), ('therapy', 'Terapiya'), ('surgery', 'Jarrohlik'), ('endocrinology', 'Endokrinologiya'), ('consilium', 'Konsilium')], max_length=20, verbose_name="Yo'nalish")),
                ('reason', models.TextField(blank=True, verbose_name="So'rov sababi / klinik savol")),
                ('status', models.CharField(choices=[('assigned', 'Yuborilgan'), ('in_progress', "Ko'rib chiqilmoqda"), ('done', 'Javob berilgan'), ('cancelled', 'Bekor qilingan')], default='assigned', max_length=15, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultants', models.ManyToManyField(blank=True, related_name='consultation_invites', to='patients.doctor', verbose_name='Taklif qilingan mutaxassislar')),
                ('patient_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_requests', to='patients.patientcard', verbose_name='Bemor kartasi')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_consultations', to='patients.doctor', verbose_name="So'rov yuborgan shifokor")),
            ],
            options={
                'verbose_name': "Konsultatsiya so'rovi",
                'verbose_name_plural': "Konsultatsiya so'rovlari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responded_at', models.DateTimeField(auto_now_add=True, verbose_name='Javob vaqti')),
                ('conclusion', models.TextField(verbose_name='Xulosa / tavsiya')),
                ('comment', models.CharField(blank=True, max_length=500, verbose_name='Izoh')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='patients.consultationrequest', verbose_name="So'rov")),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_responses', to=settings.AUTH_USER_MODEL, verbose_name='Javob bergan mutaxassis')),
            ],
            options={
                'verbose_name': 'Konsultatsiya javobi',
                'verbose_name_plural': 'Konsultatsiya javoblari',
                'ordering': ['-responded_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostic_type', models.CharField(choices=[('uzi', 'UZI'), ('rentgen', 'Rentgen'), ('mrt', 'MRT'), ('kt', 'KT'), ('ekg', 'EKG'), ('endoskopiya', 'Endoskopiya'), ('other', 'Boshqa')], max_length=20, verbose_name='Tekshiruv turi')),
                ('notes', models.TextField(blank=True, verbose_name="Klinik ko'rsatma / izoh")),
                ('status', models.CharField(choices=[('assigned', 'Tayinlangan'), ('in_progress', 'Bajarilmoqda'), ('done', 'Tayyor'), ('cancelled', 'Bekor qilingan')], default='assigned', max_length=15, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tayinlangan sana')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_diagnostics', to='patients.doctor', verbose_name='Tayinlagan shifokor')),
                ('patient_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_assignments', to='patients.patientcard', verbose_name='Bemor kartasi')),
            ],
            options={
                'verbose_name': 'Diagnostika tekshiruvi',
                'verbose_name_plural': 'Diagnostika tekshiruvlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticResultLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='Bajarilgan vaqt')),
                ('conclusion', models.TextField(blank=True, verbose_name='Xulosa')),
                ('comment', models.CharField(blank=True, max_length=500, verbose_name='Izoh')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_logs', to='patients.diagnosticassignment', verbose_name='Tekshiruv')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_diagnostics', to=settings.AUTH_USER_MODEL, verbose_name='Bajaruvchi')),
            ],
            options={
                'verbose_name': 'Diagnostika natijasi logi',
                'verbose_name_plural': 'Diagnostika natijalari loglari',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='LabTestAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255, verbose_name='Tahlil/tekshiruv nomi')),
                ('notes', models.TextField(blank=True, verbose_name="Klinik ko'rsatma / izoh")),
                ('status', models.CharField(choices=[('assigned', 'Tayinlangan'), ('sample_taken', 'Namuna olingan'), ('in_progress', 'Tekshirilmoqda'), ('done', 'Yakunlangan'), ('cancelled', 'Bekor qilingan')], default='assigned', max_length=15, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tayinlangan sana')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_lab_tests', to='patients.doctor', verbose_name='Tayinlagan shifokor')),
                ('patient_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_test_assignments', to='patients.patientcard', verbose_name='Bemor kartasi')),
            ],
            options={
                'verbose_name': 'Laboratoriya tahlili',
                'verbose_name_plural': 'Laboratoriya tahlillari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabTestResultLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='Bajarilgan vaqt')),
                ('result_text', models.TextField(blank=True, verbose_name='Natija / xulosa')),
                ('comment', models.CharField(blank=True, max_length=500, verbose_name='Izoh')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_logs', to='patients.labtestassignment', verbose_name='Tahlil')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_lab_tests', to=settings.AUTH_USER_MODEL, verbose_name='Bajaruvchi laborant')),
            ],
            options={
                'verbose_name': 'Tahlil natijasi logi',
                'verbose_name_plural': 'Tahlil natijalari loglari',
                'ordering': ['-performed_at'],
            },
        ),
    ]
