# Generated by Django 5.2.12 on 2026-06-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0028_consultationrequest_consultationresponse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcard',
            name='attending_doctor_confirmed',
            field=models.BooleanField(default=False, verbose_name='Davolovchi shifokor tasdiqlangan'),
        ),
    ]
