# Generated by Django 5.2.12 on 2026-06-19 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0029_attending_doctor_confirmed'),
        ('services', '0008_medicine_mnn_form_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_requests', to='services.service', verbose_name='Konsultatsiya xizmati (katalogdan)'),
        ),
        migrations.AddField(
            model_name='diagnosticassignment',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_assignments', to='services.service', verbose_name='Xizmat (katalogdan)'),
        ),
        migrations.AddField(
            model_name='labtestassignment',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_test_assignments', to='services.service', verbose_name='Xizmat (katalogdan)'),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='specialty',
            field=models.CharField(blank=True, choices=[('neurology', 'Nevrologiya'), ('cardiology', 'Kardiologiya'), ('therapy', 'Terapiya'), ('surgery', 'Jarrohlik'), ('endocrinology', 'Endokrinologiya'), ('consilium', 'Konsilium')], max_length=20, verbose_name="Yo'nalish"),
        ),
    ]
