# Generated by Django 5.2.12 on 2026-06-19 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0030_service_assignment_links'),
        ('services', '0009_service_assignment_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentprocedure',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_procedures', to='services.service', verbose_name='Xizmat (katalogdan)'),
        ),
    ]
