# Generated by Django 5.2.12 on 2026-06-23 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0031_treatmentprocedure_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcard',
            name='case_sheet_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Kasallik varaqasi tartib raqami'),
        ),
    ]
