# Generated by Django 5.2.12 on 2026-06-25 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0032_patientcard_case_sheet_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbulatoryConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(blank=True, verbose_name='Qabul natijasi')),
                ('recommendation', models.TextField(blank=True, verbose_name='Tavsiyalar')),
                ('conclusion', models.TextField(blank=True, verbose_name='Xulosa')),
                ('status', models.CharField(choices=[('in_progress', 'Davom etmoqda'), ('completed', 'Yakunlandi')], default='in_progress', max_length=15, verbose_name='Holati')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulatory_consultations', to='patients.doctor')),
                ('patient_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ambulatory_consultation', to='patients.patientcard')),
            ],
            options={
                'verbose_name': 'Ambulator qabul',
                'verbose_name_plural': 'Ambulator qabullar',
            },
        ),
        migrations.CreateModel(
            name='DoctorTextTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('result', 'Qabul natijasi'), ('recommendation', 'Tavsiyalar'), ('conclusion', 'Xulosa')], max_length=20, verbose_name='Turi')),
                ('title', models.CharField(max_length=150, verbose_name='Nomi')),
                ('body', models.TextField(verbose_name='Matn')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_templates', to='patients.doctor')),
            ],
            options={
                'verbose_name': 'Shifokor shabloni',
                'verbose_name_plural': 'Shifokor shablonlari',
                'ordering': ['kind', 'title'],
            },
        ),
    ]
