# Generated by Django 5.2.12 on 2026-06-25 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0033_ambulatoryconsultation_doctortexttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='cancel_reason',
            field=models.TextField(blank=True, verbose_name='Bekor qilish sababi'),
        ),
    ]
