# Generated by Django 5.2.12 on 2026-06-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0034_consultationrequest_cancel_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctortexttemplate',
            name='kind',
            field=models.CharField(choices=[('result', 'Qabul natijasi'), ('recommendation', 'Tavsiyalar'), ('conclusion', 'Xulosa'), ('complaints', 'Shikoyatlar'), ('anamnesis_morbi', 'Kasallik tarixi (Anamnesis morbi)'), ('epidemiological_anamnesis', 'Epidemiologik anamnez'), ('anamnesis_vitae', 'Hayot anamnezi (Anamnesis vitae)'), ('status_praesens', "Ob'ektiv holat (Status praesens)"), ('neurological_status', 'Nevrologik holat'), ('status_localis', 'Mahalliy holat (Status localis)'), ('lab_investigations', 'Laboratoriya va instrumental tadqiqotlar'), ('allergy_anamnesis', 'Allergoanamnesis'), ('drug_justification', 'Dori vositalari uchun asoslar')], max_length=32, verbose_name='Turi'),
        ),
    ]
