# Generated by Django 5.2.12 on 2026-06-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0035_alter_doctortexttemplate_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticresultlog',
            name='recommendation',
            field=models.TextField(blank=True, verbose_name='Tavsiya'),
        ),
    ]
