# Generated by Django 5.2.12 on 2026-06-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0036_diagnosticresultlog_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestresultlog',
            name='recommendation',
            field=models.TextField(blank=True, verbose_name='Tavsiya'),
        ),
    ]
