# Generated by Django 5.2.12 on 2026-06-25 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0037_labtestresultlog_recommendation'),
        ('services', '0010_patientmedicine_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='patient_service',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_request', to='services.patientservice', verbose_name='Hisob-faktura yozuvi'),
        ),
        migrations.AddField(
            model_name='diagnosticassignment',
            name='patient_service',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_assignment', to='services.patientservice', verbose_name='Hisob-faktura yozuvi'),
        ),
        migrations.AddField(
            model_name='labtestassignment',
            name='patient_service',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_test_assignment', to='services.patientservice', verbose_name='Hisob-faktura yozuvi'),
        ),
        migrations.AddField(
            model_name='treatmentprocedure',
            name='patient_service',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_procedure', to='services.patientservice', verbose_name='Hisob-faktura yozuvi'),
        ),
    ]
