# Generated by Django 5.2.12 on 2026-06-26 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0038_consultationrequest_patient_service_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(db_index=True, verbose_name='Rejalashtirilgan vaqt')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('done', 'Bajarildi'), ('missed', "O'tkazib yuborildi"), ('cancelled', 'Bekor qilindi')], default='pending', max_length=15, verbose_name='Holati')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Bajarilgan vaqt')),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Eslatma yuborilgan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_occurrences', to='patients.consultationrequest', verbose_name="Konsultatsiya so'rovi")),
                ('diagnostic_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_occurrences', to='patients.diagnosticassignment', verbose_name='Diagnostika tekshiruvi')),
                ('lab_test_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_occurrences', to='patients.labtestassignment', verbose_name='Laboratoriya tahlili')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_schedule_occurrences', to=settings.AUTH_USER_MODEL, verbose_name='Bajaruvchi')),
                ('treatment_procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_occurrences', to='patients.treatmentprocedure', verbose_name='Muolaja')),
            ],
            options={
                'verbose_name': 'Xizmat rejasi',
                'verbose_name_plural': 'Xizmat rejalari',
                'ordering': ['scheduled_at'],
                'indexes': [models.Index(fields=['status', 'reminder_sent_at', 'scheduled_at'], name='patients_se_status_c4f342_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('consultation_request__isnull', True), ('diagnostic_assignment__isnull', True), ('lab_test_assignment__isnull', True), ('treatment_procedure__isnull', False)), models.Q(('consultation_request__isnull', True), ('diagnostic_assignment__isnull', True), ('lab_test_assignment__isnull', False), ('treatment_procedure__isnull', True)), models.Q(('consultation_request__isnull', True), ('diagnostic_assignment__isnull', False), ('lab_test_assignment__isnull', True), ('treatment_procedure__isnull', True)), models.Q(('consultation_request__isnull', False), ('diagnostic_assignment__isnull', True), ('lab_test_assignment__isnull', True), ('treatment_procedure__isnull', True)), _connector='OR'), name='servicesched_exactly_one_target')],
            },
        ),
    ]
