# Generated by Django 5.2.12 on 2026-06-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0039_serviceschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceschedule',
            name='comment',
            field=models.TextField(blank=True, verbose_name="Izoh (nojo'ya ta'sirlar)"),
        ),
        migrations.AddField(
            model_name='serviceschedule',
            name='reason',
            field=models.TextField(blank=True, verbose_name="Bekor qilish/to'xtatish sababi"),
        ),
        migrations.AlterField(
            model_name='serviceschedule',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('done', 'Bajarildi'), ('missed', "O'tkazib yuborildi"), ('cancelled', 'Bekor qilindi'), ('stopped', "To'xtatildi")], default='pending', max_length=15, verbose_name='Holati'),
        ),
    ]
