# Generated by Django 5.2.12 on 2026-06-29 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0040_serviceschedule_comment_serviceschedule_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalexamination',
            name='selected_diagnostics',
            field=models.ManyToManyField(blank=True, related_name='cited_in_examinations', to='patients.diagnosticassignment', verbose_name='Tanlangan diagnostika natijalari'),
        ),
        migrations.AddField(
            model_name='medicalexamination',
            name='selected_lab_tests',
            field=models.ManyToManyField(blank=True, related_name='cited_in_examinations', to='patients.labtestassignment', verbose_name='Tanlangan laboratoriya natijalari'),
        ),
    ]
