# Generated by Django 5.2.12 on 2026-06-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0041_medicalexamination_selected_diagnostics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_general_practitioner',
            field=models.BooleanField(default=False, verbose_name="Terapevt (barcha bemorlarga dastlabki ko'rik)"),
        ),
    ]
