# Generated by Django 5.2.12 on 2026-06-29 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0042_doctor_is_general_practitioner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=255, verbose_name='Dori nomi')),
                ('dosage_form', models.CharField(blank=True, max_length=255, verbose_name='Форма выпуска')),
                ('dose', models.CharField(blank=True, max_length=100, verbose_name='Доза')),
                ('frequency_num', models.PositiveIntegerField(blank=True, null=True, verbose_name='Частота приёма (son)')),
                ('frequency_unit', models.CharField(blank=True, choices=[('День', 'Kuniga'), ('Неделя', 'Haftada'), ('Месяц', 'Oyda')], default='День', max_length=10, verbose_name='Частота приёма (birlik)')),
                ('single_dose', models.CharField(blank=True, max_length=50, verbose_name='Разовая доза')),
                ('method', models.CharField(blank=True, max_length=255, verbose_name='Способ применения')),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Продолжительность приёма (kun)')),
                ('intake_time', models.CharField(blank=True, max_length=10, verbose_name='Время приёма')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Davr boshi')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Davr oxiri')),
                ('total_quantity', models.CharField(blank=True, max_length=50, verbose_name='Kol-vo препарата')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yozilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='patients.doctor', verbose_name='Yozgan shifokor')),
                ('patient_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patientcard', verbose_name='Bemor kartasi')),
            ],
            options={
                'verbose_name': 'Retsept',
                'verbose_name_plural': 'Retseptlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
