# Generated by Django 5.2.12 on 2026-06-29 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0043_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='treatment_procedure',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription', to='patients.treatmentprocedure', verbose_name="Bog'langan muolaja (hamshira reja)"),
        ),
    ]
