# Generated by Django 5.2.12 on 2026-06-29 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0044_prescription_treatment_procedure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulatoryconsultation',
            name='doctor_v2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulatory_consultations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='consultants_v2',
            field=models.ManyToManyField(blank=True, related_name='consultation_invites', to=settings.AUTH_USER_MODEL, verbose_name='Taklif qilingan mutaxassislar'),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='requested_by_v2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_consultations', to=settings.AUTH_USER_MODEL, verbose_name="So'rov yuborgan shifokor"),
        ),
        migrations.AddField(
            model_name='diagnosticassignment',
            name='assigned_by_v2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_diagnostics', to=settings.AUTH_USER_MODEL, verbose_name='Tayinlagan shifokor'),
        ),
        migrations.AddField(
            model_name='doctortexttemplate',
            name='doctor_v2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labtestassignment',
            name='assigned_by_v2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_lab_tests', to=settings.AUTH_USER_MODEL, verbose_name='Tayinlagan shifokor'),
        ),
        migrations.AddField(
            model_name='patientcard',
            name='attending_doctor_v2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attending_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientcard',
            name='department_head_v2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor_v2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to=settings.AUTH_USER_MODEL, verbose_name='Yozgan shifokor'),
        ),
        migrations.AddField(
            model_name='treatmentprocedure',
            name='assigned_by_v2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_procedures', to=settings.AUTH_USER_MODEL, verbose_name='Tayinlagan shifokor'),
        ),
        migrations.AlterField(
            model_name='ambulatoryconsultation',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulatory_consultations_old', to='patients.doctor'),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='consultants',
            field=models.ManyToManyField(blank=True, related_name='consultation_invites_old', to='patients.doctor', verbose_name='Taklif qilingan mutaxassislar'),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_consultations_old', to='patients.doctor', verbose_name="So'rov yuborgan shifokor"),
        ),
        migrations.AlterField(
            model_name='diagnosticassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_diagnostics_old', to='patients.doctor', verbose_name='Tayinlagan shifokor'),
        ),
        migrations.AlterField(
            model_name='doctortexttemplate',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_templates_old', to='patients.doctor'),
        ),
        migrations.AlterField(
            model_name='labtestassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_lab_tests_old', to='patients.doctor', verbose_name='Tayinlagan shifokor'),
        ),
        migrations.AlterField(
            model_name='patientcard',
            name='attending_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attending_cards_old', to='patients.doctor'),
        ),
        migrations.AlterField(
            model_name='patientcard',
            name='department_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_cards_old', to='patients.doctor'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_old', to='patients.doctor', verbose_name='Yozgan shifokor'),
        ),
        migrations.AlterField(
            model_name='treatmentprocedure',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_procedures_old', to='patients.doctor', verbose_name='Tayinlagan shifokor'),
        ),
    ]
