# Generated by Django 5.2.12 on 2026-06-29 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0047_doctor_field_swap'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttransfer',
            name='from_dept_head_v2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_transfers_from_head', to=settings.AUTH_USER_MODEL, verbose_name="Avvalgi bo'lim mudiri"),
        ),
        migrations.AddField(
            model_name='patienttransfer',
            name='from_doctor_v2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_transfers_from_doctor', to=settings.AUTH_USER_MODEL, verbose_name='Avvalgi shifokor'),
        ),
        migrations.AddField(
            model_name='patienttransfer',
            name='to_dept_head_v2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_transfers_to_head', to=settings.AUTH_USER_MODEL, verbose_name="Yangi bo'lim mudiri"),
        ),
        migrations.AddField(
            model_name='patienttransfer',
            name='to_doctor_v2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_transfers_to_doctor', to=settings.AUTH_USER_MODEL, verbose_name='Yangi shifokor'),
        ),
        migrations.AlterField(
            model_name='patienttransfer',
            name='from_dept_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_transfers_from_head_old', to='patients.doctor', verbose_name="Avvalgi bo'lim mudiri"),
        ),
        migrations.AlterField(
            model_name='patienttransfer',
            name='from_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_transfers_from_doctor_old', to='patients.doctor', verbose_name='Avvalgi shifokor'),
        ),
        migrations.AlterField(
            model_name='patienttransfer',
            name='to_dept_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_transfers_to_head_old', to='patients.doctor', verbose_name="Yangi bo'lim mudiri"),
        ),
        migrations.AlterField(
            model_name='patienttransfer',
            name='to_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_transfers_to_doctor_old', to='patients.doctor', verbose_name='Yangi shifokor'),
        ),
    ]
