# Generated by Django 5.2.12 on 2026-06-29 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0050_patienttransfer_field_swap'),
        ('services', '0012_doctor_field_swap'),
        ('care', '0003_doctor_field_swap'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
