# Generated by Django 5.2.12 on 2026-05-20 07:09

import django.db.models.deletion
import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratory', '0003_nullable_orderitem_template'),
        ('patients', '0021_add_transfer_date_to_patient_transfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_uz', models.TextField(default='👋 Xush kelibsiz!', verbose_name='Xush kelibsiz (UZ)')),
                ('welcome_ru', models.TextField(default='👋 Добро пожаловать!', verbose_name='Xush kelibsiz (RU)')),
                ('welcome_en', models.TextField(default='👋 Welcome!', verbose_name='Xush kelibsiz (EN)')),
                ('about_uz', models.TextField(blank=True, verbose_name='Klinika haqida (UZ)')),
                ('about_ru', models.TextField(blank=True, verbose_name='Klinika haqida (RU)')),
                ('contacts', models.JSONField(blank=True, default=dict, help_text='{"phone": "+998...", "email": "...", "maps": "..."}', verbose_name='Kontaktlar')),
                ('working_hours', models.JSONField(blank=True, default=dict, help_text='{"mon-fri": "08:00-18:00", "sat": "08:00-14:00"}', verbose_name='Ish vaqti')),
                ('is_maintenance', models.BooleanField(default=False, verbose_name='Texnik ishlar rejimi')),
                ('maintenance_msg', models.TextField(blank=True, verbose_name='Texnik ishlar xabari')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bot sozlamalari',
                'verbose_name_plural': 'Bot sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=64, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=64, verbose_name='Ismi')),
                ('last_name', models.CharField(blank=True, max_length=64, verbose_name='Familiyasi')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('language_code', models.CharField(choices=[('uz', "O'zbek"), ('ru', 'Русский'), ('en', 'English')], default='uz', max_length=5, verbose_name='Til')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Tasdiqlangan')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Bloklangan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Ro'yxatdan o'tgan")),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Oxirgi faollik')),
            ],
            options={
                'verbose_name': 'Telegram foydalanuvchi',
                'verbose_name_plural': 'Telegram foydalanuvchilar',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='ResultFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name="Fayl yo'li")),
                ('telegram_file_id', models.CharField(blank=True, max_length=200, verbose_name='Telegram file_id (cache)')),
                ('secure_token', models.CharField(default=secrets.token_urlsafe, max_length=64, unique=True, verbose_name='Xavfsiz token')),
                ('expires_at', models.DateTimeField(verbose_name='Muddati')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Yuklab olishlar')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('lab_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_file', to='laboratory.labresult', verbose_name='Lab natijasi')),
            ],
            options={
                'verbose_name': 'Natija PDF fayli',
                'verbose_name_plural': 'Natija PDF fayllari',
            },
        ),
        migrations.CreateModel(
            name='PatientTelegramBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('verified', 'Tasdiqlangan'), ('blocked', 'Bloklangan')], default='verified', max_length=10, verbose_name='Holat')),
                ('bound_phone', models.CharField(max_length=20, verbose_name='Tasdiqlangan raqam')),
                ('bound_at', models.DateTimeField(auto_now_add=True, verbose_name="Bog'langan vaqt")),
                ('patient_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_bindings', to='patients.patientcard', verbose_name='Bemor kartasi')),
                ('telegram_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_binding', to='telegram_bot.telegramuser', verbose_name='Telegram foydalanuvchi')),
            ],
            options={
                'verbose_name': "Bemor-Telegram bog'lanishi",
                'verbose_name_plural': "Bemor-Telegram bog'lanishlari",
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(verbose_name='Telegram ID')),
                ('action', models.CharField(choices=[('start', '/start'), ('auth', 'Autentifikatsiya'), ('auth_fail', 'Autentifikatsiya xatosi'), ('view_results', "Natijalar ko'rish"), ('view_result', "Natija ko'rish"), ('download_pdf', 'PDF yuklab olish'), ('menu', 'Menyu'), ('price_view', "Narxlar ko'rish"), ('blocked', 'Bloklandi'), ('error', 'Xato')], max_length=20, verbose_name='Amal')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='Tafsilot')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
                ('telegram_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='telegram_bot.telegramuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Audit log',
                'verbose_name_plural': 'Audit loglar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResultNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Yuborilmagan'), ('sent', 'Yuborildi'), ('seen', "Ko'rildi"), ('failed', 'Xato')], default='pending', max_length=10, verbose_name='Holat')),
                ('message_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram xabar ID')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Yuborilgan vaqt')),
                ('seen_at', models.DateTimeField(blank=True, null=True, verbose_name="Ko'rilgan vaqt")),
                ('retry_count', models.PositiveSmallIntegerField(default=0, verbose_name='Urinishlar soni')),
                ('error_msg', models.TextField(blank=True, verbose_name='Xato matni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='laboratory.labresult', verbose_name='Lab natijasi')),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='telegram_bot.telegramuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['-created_at'],
                'unique_together': {('telegram_user', 'lab_result')},
            },
        ),
    ]
